#!/bin/bash

# Get command line parameters
DRC_CFG_FILE="${1}"
IMPULSE_FILE="$2"
FILTER_FILE="$3"
CURR_CHANNEL="$4"
RATE="44100"
# defaults
TMP="/tmp"
SOX="sox"

filename=$(basename "$IMPULSE_FILE")
extension="${filename##*.}"
PCM_IMP_FILENAME=${TMP}/impulse_chanel$CURR_CHANNEL.pcm
echo "extension : " $extension
if [ "$extension" == "wav" ]; then
	REMIX_PARAM="remix "$((CURR_CHANNEL + 1))
	echo "wavefile -> converting to pcm for DRC with remix param : "$REMIX_PARAM
	$SOX $IMPULSE_FILE -t raw -r $RATE -e float -b 32 -c 1 $PCM_IMP_FILENAME $REMIX_PARAM
else
	echo "pcm filer file -> just copy"
 	cp $IMPULSE_FILE $PCM_IMP_FILENAME
fi

echo DRCCfgFile : $DRC_CFG_FILE
echo "calculating filters"
PCM_FILTER=${TMP}/filter.pcm
drc --BCInFile=$PCM_IMP_FILENAME --PSOutFile=$PCM_FILTER --TCOutFile=test.pcm "${DRC_CFG_FILE}"
sox -t raw -r $RATE -c 1 -e float -b32 ${PCM_FILTER} -t wav ${FILTER_FILE}
