#!/bin/bash

# Get command line parameters
DRC_CFG_FILE="$1"
IMPULSE_FILE="$2"
FILTER_FILE="$3"


echo DRCCfgFile : $DRC_CFG_FILE
echo "calculating filters"
drc --BCInFile=$IMPULSE_FILE --PSOutFile=$FILTER_FILE --TCOutFile=test.pcm "${DRC_CFG_FILE}"
