#!/bin/bash

# Automatic measuring script
# Copyright (C) 2002-2005 Denis Sbragion

# This program may be freely redistributed under the terms of
# the GNU GPL and is provided to you as is, without any warranty
# of any kind. Please read the file "COPYING" for details.

# Useful programs
ECHO="echo"
RM="rm"
MV="mv"
GLSWEEP="glsweep"
SOX="sox"
LSCONV="lsconv"
APLAY="aplay"
ARECORD="arecord"
SYNC="sync"
SLEEP="sleep"
TEST_MODE=false

# Default parameters
TMP="/tmp"
LEADIN="0.05"
LEADOUT="0.005"
MINGAIN="0.1"
DLSTART="0.9"

$ECHO 
$ECHO "Automatic measuring script."
$ECHO "Copyright (C) 2002-2005 Denis Sbragion"
$ECHO 
$ECHO "This program may be freely redistributed under the terms of"
$ECHO "the GNU GPL and is provided to you as is, without any warranty"
$ECHO "of any kind. Please read the file "COPYING" for details."
$ECHO 

# Command line check
if [[ $# < 11 ]]; then
 $ECHO "Usage:"
 $ECHO " measure bits rate startf endf lslen lssil indev outdev impfile"
 $ECHO
 $ECHO " bits: measuring bits (16 or 24)"
 $ECHO " rate: sample rate"
 $ECHO " startf: sweep start frequency in Hz"
 $ECHO " endf: sweep end frequency in Hz"
 $ECHO " lslen: log sweep length in seconds"
 $ECHO " lssil: log sweep silence length in seconds"
 $ECHO " indev: ALSA input device"
 $ECHO " outdev: ALSA output device"
 $ECHO " amplitude of sweep file 0.1 .. 1" 
 $ECHO " recording chanel to use (device dependend 1..n)" 
 $ECHO "example: measure 16 44100 5 21000 45 2 plughw plughw impulse.pcm use_ref"
 $ECHO
 exit 0
fi 

# Get command line parameters
BITS="$1"
RATE="$2"
STARTF="$3"
ENDF="$4"
LSLEN="$5"
LSSIL="$6"
INDEV="$7"
OUTDEV="$8"
IMPFILE="$9"
AMPLITUDE="${10}"
REC_CHANNEL="${11}"
PLAY_CHANNEL="${12}"
SWEEPFILE="sweep.pcm"
ARECORDFMT="S32_LE"
SOXFMT="-e signed-integer -b 32"

# Generate the log sweep
$ECHO "all parameters " $BITS $RATE $STARTF $ENDF $LSLEN $LSSIL $INDEV $OUTDEV $IMPFILE $AMPLITUDE $REC_CHANNEL $PLAY_CHANNEL

# determine channel to play the sweep to

if [ -z "$PLAY_CHANNEL" ]; then
 PLAY_SWEEP_PARAM=""
elif [ "$PLAY_CHANNEL" == "l" ]; then
 PLAY_SWEEP_PARAM="remix 1 0"
elif [ "$PLAY_CHANNEL" == "r" ]; then
 PLAY_SWEEP_PARAM="remix 0 1"
fi

$ECHO "PLAY_SWEEP_PARAM : " $PLAY_SWEEP_PARAM

$ECHO "generating sweep " $RATE $AMPLITUDE $STARTF $ENDF $LSLEN $LSSIL $LEADIN $LEADOUT ${TMP}/msrawsweep.pcm ${TMP}/msinverse.pcm
$GLSWEEP $RATE $AMPLITUDE $STARTF $ENDF $LSLEN $LSSIL $LEADIN $LEADOUT ${TMP}/msrawsweep.pcm ${TMP}/msinverse.pcm

# Convert to WAV file
$ECHO "Converting sweep to play format..."
$SOX -t raw -r $RATE -c 1 -e float -b32 ${TMP}/msrawsweep.pcm -t wav -c 2 $SOXFMT ${TMP}/msplaysweep.wav $PLAY_SWEEP_PARAM

# Filesystem sync
$ECHO "Waiting 5 seconds for filesystem sync..."
$SYNC
$SLEEP 5

# Record the sweep
$ECHO "Sweep recording."
$SLEEP 1
RLEN=$(( $LSLEN + $LSSIL * 2 ))
REC_WAV_NAME=${TMP}/msrecsweep${PLAY_CHANNEL}.wav
REC_PCM_NAME=${TMP}/msrecsweep${PLAY_CHANNEL}.pcm
if [ $TEST_MODE == true ]; then\
		$ECHO "simulating record!!!\n"
		#$APLAY -D $OUTDEV ${TMP}/msplaysweep.wav
		i=10
		LOOP_AMPLITUDE=$(bc <<< "scale=2;$AMPLITUDE +($i/10)")
		SIM_AMPLITUDE=$LOOP_AMPLITUDE
		$ECHO "Sim Amplitude: "$SIM_AMPLITUDE" to : "$REC_WAV_NAME" and : "$REC_PCM_NAME
		$ECHO $GLSWEEP $RATE $SIM_AMPLITUDE $STARTF $ENDF $LSLEN $LSSIL $LEADIN $LEADOUT $REC_PCM_NAME ${TMP}/dummy_inverse.pcm
		$GLSWEEP $RATE $SIM_AMPLITUDE $STARTF $ENDF $LSLEN $LSSIL $LEADIN $LEADOUT $REC_PCM_NAME ${TMP}/dummy_inverse.pcm
		$SOX -t raw -r $RATE -c 1 -e float -b32 $REC_PCM_NAME -t wav $SOXFMT $REC_WAV_NAME
	else
		$APLAY -D $OUTDEV ${TMP}/msplaysweep.wav &
		$ARECORD -D $INDEV -t wav -r $RATE -f $ARECORDFMT -c 2 -d $RLEN $REC_WAV_NAME
fi

$ECHO "recorded sweep conversion"
$SOX $REC_WAV_NAME -t raw -r $RATE -e float -b 32 -c 1 $REC_PCM_NAME remix 1 0

IMP_FILE_PCM="${TMP}/measured_impulse${PLAY_CHANNEL}.pcm"

# Extract the impulse response
$LSCONV $REC_PCM_NAME ${TMP}/msinverse.pcm $IMP_FILE_PCM $REF_PARAM 


#convert the result to wav
$ECHO -t raw -r $RATE -c 1 -e float -b32 $IMP_FILE_PCM -t wav $IMPFILE
$SOX -t raw -r $RATE -c 1 -e float -b32 $IMP_FILE_PCM -t wav $SOXFMT $IMPFILE

$ECHO "Temporary file cleanup..."

# cleanup
#$RM ${TMP}/*.pcm
#$RM ${TMP}/*.wav
