#!/bin/bash

# Get command line parameters
ALSA_PLAY_HARDWARE="$1"
RATE="44100"
WAV_FILTER_FILE="$2"

if [[ $# < 2 ]]; then
	echo "disabling brutefir: setting pass-through filters"
	# disable bruteFIR filter --> set -1 for all coeffs with telnet cfc command 
	echo "cfc 0 -1;cfc 1 -1" | nc localhost 3000
	# make ALSA_PLAY_HARDWARE the default again
else
	sudo pkill brutefir
	echo "runnign sox to create bruteFIR pcm filters"
	sox $WAV_FILTER_FILE -t raw -c 1 ~/filter_l.pcm remix 1
	sox $WAV_FILTER_FILE -t raw -c 1 ~/filter_r.pcm remix 2

	#create and update bruteFIR cfg if not existing, install if not existing, enable alsa loopback device etc....
	grep -q "filter_l.pcm" ~/.brutefir_config
	if [ $? == 1 ]; then
		cp /usr/share/rhythmbox/plugins/DRC/.brutefir_config ~/
		cp /usr/share/rhythmbox/plugins/DRC/.brutefir_defaults ~/
	fi
	#TODO upate brutefir cfg with correct audio devices (loopback --> alsa out)

	sudo apt-get install snd-aloop brutefir
	#insert snd-aloop into snd-aloop
	grep -q "snd-aloop" /etc/modules
	if [ $? == 1 ]; then
		sudo sh -c "echo \"snd-aloop\" >> /etc/modules"
		sudo modprobe snd-aloop
	fi
	#start brutefir as sudo
	sudo brutefir ~/.brutefir_config &
fi
